sonar.projectKey=nightwalker9999_devops-hands-on-project-hivebox
sonar.organization=nightwalker9999
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
