apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hivebox
  template:
    metadata:
      labels:
        app: hivebox
    spec:
      containers:
        - name: hivebox
          image: ghcr.io/nightwalker9999/hivebox:latest
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /version
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5